#!/bin/sh
"""true"
BASE_DIR="$(cd "$(dirname "$0")"; pwd)"
ENV_DIR="$BASE_DIR/venv/bin"
PYTHON="python3"
INTERPRETER="$ENV_DIR/$PYTHON"
exec $INTERPRETER "$0" "$@"
exit 127
"""
# -*- coding: utf-8 -*-
#
# Copyright (c) 2022 Busana Apparel Group. All rights reserved.
#
# This product and it's source code is protected by patents, copyright laws and
# international copyright treaties, as well as other intellectual property
# laws and treaties. The product is licensed, not sold.
#
# The source code and sample programs in this package or parts hereof
# as well as the documentation shall not be copied, modified or redistributed
# without permission, explicit or implied, of the author.
#
# This module is part of Centric PLM Integration Bridge and is released under
# the Apache-2.0 License: https://www.apache.org/licenses/LICENSE-2.0

import sys
import os
import re
from common import consts
from ibridge import main

if __name__ == '__main__':
    consts.DEF_SCRIPT_PATH = os.path.dirname(os.path.abspath(__file__))
    print(consts.DEF_SCRIPT_PATH)
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
