#!/bin/sh
"""true"
BASE_DIR="$(cd "$(dirname "$0")"; pwd)"
ENV_DIR="$BASE_DIR/venv/bin"
PYTHON="python3"
INTERPRETER="$ENV_DIR/$PYTHON"
exec $INTERPRETER "$0" "$@"
exit 127
"""
# -*- coding: utf-8 -*-
import re
import sys
from gunicorn.app.wsgiapp import run
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(run())
